print('Praktikum Algortima dan Pemrograman 1 - Variablel dan Tipe Data')
print(False)
print("Ini adalah tulisan berupa String")
print(100)
print(1.e-3)
print('bilangan desimal dari 0x01 adalah',0x01)
print(10)
print(2+6j)
print([96,97,98,99,100])
print(['seratus','dua ratus','tiga ratus'])
print({'nama':'Ani','umur':19})
print('This string contains a single quote(\') character')
